# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class chatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextMessage = channel.unary_unary(
                '/chat/TextMessage',
                request_serializer=chat__pb2.TextMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.ServerAcknowledge.FromString,
                )
        self.ChannelJoin = channel.unary_unary(
                '/chat/ChannelJoin',
                request_serializer=chat__pb2.ChannelJoinRequest.SerializeToString,
                response_deserializer=chat__pb2.ServerAcknowledge.FromString,
                )


class chatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelJoin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_chatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.TextMessage,
                    request_deserializer=chat__pb2.TextMessageRequest.FromString,
                    response_serializer=chat__pb2.ServerAcknowledge.SerializeToString,
            ),
            'ChannelJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelJoin,
                    request_deserializer=chat__pb2.ChannelJoinRequest.FromString,
                    response_serializer=chat__pb2.ServerAcknowledge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat/TextMessage',
            chat__pb2.TextMessageRequest.SerializeToString,
            chat__pb2.ServerAcknowledge.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChannelJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat/ChannelJoin',
            chat__pb2.ChannelJoinRequest.SerializeToString,
            chat__pb2.ServerAcknowledge.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
